// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTcua8gGKt9wm1sAmqGNFxw6F-BDg9Y6k',
    appId: '1:465537717851:web:4c1de7ffd7f7287bda517e',
    messagingSenderId: '465537717851',
    projectId: 'beach-combine-5d3de',
    authDomain: 'beach-combine-5d3de.firebaseapp.com',
    storageBucket: 'beach-combine-5d3de.appspot.com',
    measurementId: 'G-K9PGDFXRD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBajYoyWxX6n42jc-ULBkZEo0UoJb48VdY',
    appId: '1:465537717851:android:95bd93afcbb5c0b1da517e',
    messagingSenderId: '465537717851',
    projectId: 'beach-combine-5d3de',
    storageBucket: 'beach-combine-5d3de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIsO8THLAARnAjYXaLfH3reVsQDEjcHZQ',
    appId: '1:465537717851:ios:77ddff7cf799ca01da517e',
    messagingSenderId: '465537717851',
    projectId: 'beach-combine-5d3de',
    storageBucket: 'beach-combine-5d3de.appspot.com',
    iosClientId:
        '465537717851-eec289j99qgadgu54df5t369sev0k21o.apps.googleusercontent.com',
    iosBundleId: 'com.example.beachCombine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIsO8THLAARnAjYXaLfH3reVsQDEjcHZQ',
    appId: '1:465537717851:ios:77ddff7cf799ca01da517e',
    messagingSenderId: '465537717851',
    projectId: 'beach-combine-5d3de',
    storageBucket: 'beach-combine-5d3de.appspot.com',
    iosClientId:
        '465537717851-eec289j99qgadgu54df5t369sev0k21o.apps.googleusercontent.com',
    iosBundleId: 'com.example.beachCombine',
  );
}
